export const BUY_FLIGHT = 'BUY_FLIGHT';
export const ADD_PASSENGERS = 'ADD_PASSENGERS';
export const ADD_CONTACT_INFO = 'ADD_CONTACT_INFO';
export const ADD_BILLING_INFO = 'ADD_BILLING_INFO';
export const ADD_INSURANCE_INFO = 'ADD_INSURANCE_INFO';



